config/routes.rb
Rails.application.routes.draw do

  root 'categories#index'
  resources :categories
  resources :posts

  resources :categories do
    resources :posts 
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  resources :users
  resources :sessions

  post '/search' => 'posts#search'

  get '/slideshow' => 'posts#slideshow'

  get '/archive/:month' => 'categories#archive'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  private

  def current_user
   	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
  	redirect_to new_user_path unless current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
		@posts = Post.order(created_at: :desc).limit(6)
		@posts_month = Post.all.group_by { |post| post.created_at.strftime("%B %Y")}
	end

	def new
		@category = Category.new
	end
	def create
		@category = Category.create(category_params)
		redirect_to '/categories'
	end

	def show
		@category = Category.find(params[:id])
		@posts = Post.where(category_id: @category.id)
		@is_category_creator = session[:user_id] == @category.created_by
		@category_user_name = User.find(@category.created_by).username
		@posts_month = Post.all.group_by { |post| post.created_at.strftime("%B %Y")}
		# @posts_month = Post."group_by_#{month}"(:created_at)
	end

	def archive
		@month = params[:month]
		
		@month.sub!("January ", "01-")
		@month.sub!("February ", "02-")
		@month.sub!("March ", "03-")
		@month.sub!("April ", "04-")
		@month.sub!("May ", "05-")
		@month.sub!("June ", "06-")
		@month.sub!("July ", "07-")
		@month.sub!("August ", "08-")
		@month.sub!("September ", "09-")
		@month.sub!("October ", "10-")
		@month.sub!("November ", "11-")
		@month.sub!("December ", "12-")


		# @posts = Post.where('extract(month  from timestamp) = ?', @month)
		puts "QUERY going to postgres"
		puts Post.where("to_char(created_at, 'MM-YYYY') = ? ", params[:month]).explain
		@posts = Post.where("to_char(created_at, 'MM-YYYY') = ? ", params[:month])
		# @posts = Post.where('extract(month  from created_at) = ?', @month)
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update(category_params)
		redirect_to @category
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to '/categories'
	end

	private
	def category_params
		params.require(:category).permit(:title, :content, :image, :author, :created_by)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
	end

	def create
		@category = Category.find(params[:category_id])
		@post = @category.posts.create(post_params)
		redirect_to @category
	end

	def show
		@category = Category.find(params[:category_id])
		@post = Post.find(params[:id])
		@is_creator = session[:user_id] == @post.created_by
		@user_name = User.find(@post.created_by).username
		@posts_month = Post.all.group_by { |post| post.created_at.strftime("%B %Y")}
	end

  	def search

  		@query = params[:search]
  		search_condition = "%" + @query + "%"
  		# search_condition = "%" + params[:search] + "%"
  		puts params[:search]

		@results = Post.where("title ILIKE ? OR content ILIKE ? ", search_condition, search_condition)	
	end

	def slideshow
		@posts = Post.order(created_at: :desc)
	end


	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to category_post_path
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to '/categories'
	end

	private
	def post_params
		params.require(:post).permit(:title, :content, :image, :author, :category_id, :created_by)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		user = User.find_by(username: params[:username])

		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to categories_path
		else
			@error = "username and password are not in system"
			render :new
		end
	end

	def destroy
		reset_session
		redirect_to categories_path :notice => "Logged out"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		user = User.create(username: params[:username], password: params[:password])
		session[:user_id] = user.id
		redirect_to categories_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/archive.html.erb
<head>
		<link href='https://fonts.googleapis.com/css?family=Droid+Serif|Lobster|Yanone+Kaffeesatz|Crimson+Text' rel='stylesheet' type='text/css'>
</head>
<style>
	body {
		margin-top: 70px;
		overflow-x: hidden;
		font-family: Crimson Text;
		font-size: 17px;
	}
	hr {
		border-color: #b3b3b3;
		/*width: 90%;*/
	}
	h2 {
		text-align: center;
	}
	.row {
    	margin-right: -15px;
    	margin-left: -15px;
	}
	.container {
    	padding-right: 15px;
    	padding-left: 15px;
    	margin-right: auto;
    	margin-left: auto;
	}
</style>
		<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li>
          	<% if current_user %>
							<li><a method="GET" href="/logout">Logout</a></li>
						<% end %>
						<li><%= link_to 'Login', '/sessions/new' %></li>
						<li><%= link_to 'Sign Up', '/users/new' %></li>
          </ul>
        </div>
      </div>
   	</div>
   	<div class="container">
			<div class = "row" %>
				<div class = "col-md-8 col-md-offset-2">
					<h2> Archive Page</h2>
					<h3><%= @month %></h3>
					<% @posts.each do |post| %>
						<h3><%= post.title %></h3>
						<img style = "width:95%;height:300px;" src="<%= post.image %>"></br>
						<p style="width:100%"><%= post.content[0...150] %>...</p>
					<hr>
					<% end %>
				</div>
			</div>
		</div>

	
								

app/views/categories/edit.html.erb
<head>
		<link href='https://fonts.googleapis.com/css?family=Droid+Serif|Lobster|Yanone+Kaffeesatz|Crimson+Text' rel='stylesheet' type='text/css'>
</head>

<style>
	input[type="text"] {
		width: 100%;
		font-size: 20px;
		border-radius: 5px;

	}
	textarea {
		width: 100%;
		height: 200px;
		font-size: 20px;
		border-radius: 5px;
	}

	body {
		margin-top: 70px;
		/*overflow-x: hidden;*/
		font-family: Crimson Text;
		font-size: 17px;
	}
	.btn-secondary {
		width: 100%;
		font-size: 20px;
		background-color: #3fb2bb;
		color: white;
	}
	.row {
    	margin-right: -15px;
    	margin-left: -15px;
	}	
	.container {
    	padding-right: 15px;
    	padding-left: 15px;
    	margin-right: auto;
    	margin-left: auto;
	}
	h1 {
		text-align: center;
	}
/*	f.label {
		font-size: 20px;
	}*/
</style>

	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li>
          </ul>
        </div>
      </div>
   	</div>



<div class="container">
	<div class = "row">
		<div class = "col-md-6 col-md-offset-3">
			<h1>Edit Category "<%= @category.title %>" here</h1>
			<%= form_for @category, url: {action: 'update'} do |f| %>
				<h3><%= f.label :Title %>:</h3>
				<%= f.text_field :title,  value: @category.title %>
				</br></br>

				<h3><%= f.label :Content %>:</h3>
				<%= f.text_area :content, value: @category.content %>
				</br></br>

				<h3><%= f.label :Image %>:</h3>
				<%= f.text_field :image, value: @category.image %>
				</br></br>

				<%= f.submit 'Update Category!', :class => "btn btn-secondary"%>
			<% end %>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<head>

	</head>

<style>
	img {
		height: 100px;
		width: 100px;
	}
	hr {
		border-color: #b3b3b3;
	}
	p {
		/*text-align: justify;*/
	}
	body {
		font-family: 18px;
		margin-top: 70px;
		font-size: 17px;
		font-family: Crimson Text;
	}
	#search_field {
		width:70%;
		height: 30px;
		font-size: 18px;
		margin-right: 10px;
		padding-right: 10px;
		padding-left: 5px;
	}
	.three-col {
 		 -webkit-columns: 3 195px;
     	-moz-columns: 3 195px;
       	columns: 3 195px;
	}
	.button {
		height: 30px;
		font-size: 18px;
		background-color: #3fb2bb;
		color: white;
		padding-bottom: 15px;
	}
	.row {
    	margin-right: -15px;
    	margin-left: -15px;
	}
	.container {
    	padding-right: 15px;
    	padding-left: 15px;
    	margin-right: auto;
    	margin-left: auto;
	}



	</style>
	
	  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li> 
          	<% if current_user %>
							<li><%= link_to 'New Category', '/categories/new' %></li> 
							<li><a method="GET" href="/logout">Logout</a></li> 
						<% end %>
						<li><%= link_to 'Login', '/sessions/new' %></li> 
						<li><%= link_to 'Sign Up', '/users/new' %></li> 
          </ul>
        </div>
      </div>
   	</div>
   	<div class = "container">
			<div class = "row">
				<div class = "col-md-10 col-md-offset-1">
					<div class = "row">
						<div class = "col-md-8">
						
							<img src='/assets/DSC06875.JPG' style="width:100%;height:300px;"/></br></br></br>
							<p class="three-col">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Aenean lacinia bibendum nulla sed consectetur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean lacinia bibendum nulla sed consectetur. Nullam quis </p>

																	<hr>
							<h2>Latest Posts</h2></br>
							<% @posts.each do |post| %>
								<img style = "width:100%;height:300px;" src="<%= post.image %>"/></br></br>
								<h3><%= post.title %></h3></br>
								 <%= post.created_at %></br></br>
								<p class = "three-col"><%= post.content[0...200] %>...</p></br>
								<hr></br>
							<% end %>
						</div>
						<div class = "col-md-4" style="padding-left:30px;">
							<div class = "row">
								<div class = "col-md-12">
									<h5>SEARCH</h5></br>
							 		<%= form_tag :controller => 'posts', :action => 'search', :method => 'get'  do %>
      							<%= text_field_tag :search, params[:search], placeholder: "Search for .....", :id => 'search_field' %>
      							<%= submit_tag "Search", :name => nil, class: "button" %>
  								<% end %>
								</div>
							</div>
							</br>
					<hr>
							<div class = "row">
								<div class = "col-md-12">
									<h5>CATEGORIES</h5></br>
										<% @categories.each do |category| %>
											<%= link_to (category.title), category %></br>
										<% end %>
								</div>
							</div></br>
					<hr>
							<div class = "row">
								<div class = "col-md-12">
									<h5>ARCHIVES</h5></br>
    							<% @posts_month.each do |month, posts| %>
    								<a href='/archive/<%= month %>'><%= month %></a></br>
    							<% end %>
								</div>
							</div>
					<hr>
							<div class = "row">
								<h5 style="padding-left:12px;">FEATURED GALLERY</h5></br>
								<% @posts.each do |post| %>
									<div class = "col-md-4 col-xs-4" style="padding-bottom:8px;">
										<%= link_to image_tag(post.image), '/slideshow' %>
									</div>
								<% end %>
							</div>
					<hr>
					</div>				
				</div>
			</div>
			</div>
		</div>
		</div>





					

app/views/categories/new.html.erb
<style>
	input[type="text"] {
		width: 100%;
		font-size: 20px;
		border-radius: 5px;
		padding-left: 5px;

	}
	textarea {
		width: 100%;
		height: 200px;
		font-size: 20px;
		border-radius: 5px;
		padding-left: 5px;
	}

	body {
		margin-top: 70px;
		font-family: Crimson Text;
		font-size: 17px;
		/*overflow-x: hidden;*/
	}
	.btn-secondary {
		width: 100%;
		font-size: 20px;
		background-color: #3fb2bb;
		color: white;
	}
	.row {
    	margin-right: -15px;
    	margin-left: -15px;
	}
	.container {
    	padding-right: 15px;
    	padding-left: 15px;
    	margin-right: auto;
    	margin-left: auto;
	}
	h1 {
		text-align: center;
	}

</style>



	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li>
          </ul>
        </div>
      </div>
   	</div>
   	<div class = "container">
   <div class = "row">
   	<div class = "col-md-6 col-md-offset-3">
   		<h1>Create a category</h1>
			<%= form_for @category, url: {action: 'create'} do |f| %>
				<h3><%= f.label :Title %>:</h3>
				<%= f.text_field :title %>
				</br></br>

				<h3><%= f.label :Content %>:</h3>
				<%= f.text_area :content %>
				</br></br>

				<h3><%= f.label :Image %>:</h3>
				<%= f.text_field :image %>
				</br></br>

				<%= f.hidden_field :created_by, value: session[:user_id] %>



				<%= f.submit 'Create a new Category!', :class => "btn btn-secondary" %>
			<% end %>
		</div>
	</div>	
</div>

app/views/categories/show.html.erb
<head>
	<link href='https://fonts.googleapis.com/css?family=Droid+Serif|Lobster|Yanone+Kaffeesatz|Crimson+Text' rel='stylesheet' type='text/css'>
</head>

<style>
	img {
		width: 100px;
		height: 100px;
	}
	hr {
		border-color: #b3b3b3;
	}
	.three-col {
 		 -webkit-columns: 3 180px;
     	-moz-columns: 3 180px;
       	columns: 3 180px;
	}
	body {
		margin-top: 70px;
		font-family: Crimson Text;
		font-size: 17px;
	}

	.button {
		height: 30px;
		font-size: 18px;
		background-color: #3fb2bb;
		color: white;

	}
	#search_field {
		height: 30px;
		width:70%;
		font-size: 18px;
		margin-right: 10px;
		padding-right: 10px;
		padding-left: 5px;
	}
	.row {
    	margin-right: -15px;
    	margin-left: -15px;
	}
	.container {
    	padding-right: 15px;
    	padding-left: 15px;
    	margin-right: auto;
    	margin-left: auto;
	}

</style>
	
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li>
          	<% if current_user %>
          		<li><%= link_to 'New Post', '/categories/' + @category.id.to_s + '/posts/new' %></li>
          	<% end %>
          	<% if @is_category_creator %>
          		<li><%= link_to 'Delete', @category, method: :delete %></li>
							<li><%= link_to 'Edit', '/categories/' + @category.id.to_s + '/edit' %></li>
						<% end %>
						<% if current_user %>
          		<li><a method="GET" href="/logout">Logout</a></li>
          	<% end %>			
						<li><%= link_to 'Login', '/sessions/new' %></li>
						<li><%= link_to 'Sign Up', '/users/new' %></li>
          </ul>
        </div>
      </div>
   	</div>
	
   	<div class = "container">
	<div class = "row">
		<div class = "col-md-10 col-md-offset-1">
			<div class = "row">
				<div class = "col-md-8">
					<img style="width:100%; height:300px;"src="<%= @category.image %>"></br></br>						
						<h3><%= @category.title %></h3></br>
						by <b><%= @category_user_name.upcase %></b> created at <%= @category.created_at %></br></br>
						
							<p class = "three-col"><%= @category.content %></p>
				</div>
				<div class = "col-md-4" style="padding-left:30px;">
					<hr>
					<div class = "row">
						<div class = "col-md-12">
							<h5>SEARCH</h5></br>
							<%= form_tag :controller => 'posts', :action => 'search', :method => 'get'  do %>
      					<%= text_field_tag :search, params[:search], placeholder: "Search for .....", :id => 'search_field' %>
      					<%= submit_tag "Search", :name => nil, class: "button" %> 
  						<% end %>
  					</div>
  				</div></br>
  				<hr>
  				<div class = "row">
  					<div class = "col-md-12">
  						<h5>POSTS</h5></br>
							<% @category.posts.each do |post| %>
								<%= link_to (post.title), '/categories/' + @category.id.to_s + '/posts/' + post.id.to_s %></br>
							<% end %>
						</div>
					</div></br>
					<hr>
					<div class = "row">
						<div class = "col-md-12">
							<h5>ARCHIVES</h5></br>
    						<% @posts_month.each do |month, posts| %>
    							<a href='/archive/<%= month %>'><%= month %></a></br>
    						<% end %>
						</div>
					</div>
					<hr>
					<div class = "row">
						<h5 style="padding-left:12px;">FEATURED GALLERY</h5></br>
						<% @category.posts.each do |post| %>
							<div class = "col-md-4 col-xs-6" style="padding-bottom:8px;">
								<%= link_to image_tag(post.image), '/slideshow' %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif|Lobster|Yanone+Kaffeesatz|Crimson+Text' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link href='https://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>  
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<!-- 	<div id="search" %>

	</div> -->
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<style>
	input[type="text"] {
		width: 100%;
		font-size: 20px;
		border-radius: 5px;

	}
	textarea {
		width: 100%;
		height: 200px;
		font-size: 20px;
		border-radius: 5px;
	}
	body {
		margin-top: 70px;
		font-family: Crimson Text;
		font-size: 17px;
	}
	.btn-secondary {
		width: 100%;
		font-size: 20px;
		background-color: #3fb2bb;
		color: white;
	}
	.row {
    	margin-right: -15px;
    	margin-left: -15px;
	}
	.container {
    	padding-right: 15px;
    	padding-left: 15px;
    	margin-right: auto;
    	margin-left: auto;
	}
	h1 {
		text-align: center;
	}
</style>

	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li>
          </ul>
        </div>
      </div>
   	</div>
		<div class="container">
			<div class = "row">
				<div class = "col-md-6 col-md-offset-3">
					<h1>Edit Post "<%= @post.title %>"</h1>
					<%= form_for @post, url: {action: 'update'} do |f| %>
						<h3><%= f.label :Title %>:</h3>
						<%= f.text_field :title,  value: @post.title %>
						</br></br>

						<h3><%= f.label :Content %>:</h3>
						<%= f.text_area :content, value: @post.content %>
						</br></br>

						<h3><%= f.label :Image %>:</h3>
						<%= f.text_field :image, value: @post.image %>
						</br></br>

						<%= f.submit 'Update Post!', :class => "btn btn-secondary" %>
					<% end %>
				</div>
			</div>
		</div>

app/views/posts/show.html.erb
<style>
	.three-col {
     -webkit-columns: 3 180px;
      -moz-columns: 3 180px;
        columns: 3 180px;
	}
  body {
    margin-top: 70px;
    font-family: Crimson Text;
    font-size: 17px;
  }
  #search {
    font-size: 18px;
  }
  .button {
    height: 30px;
    font-size: 18px;
    background-color: #3fb2bb;
    color: white;
  }
  #search_field {
    height: 30px;
    width:70%;
    font-size: 18px;
    margin-right: 10px;
    padding-right: 10px;
    padding-left: 5px;
  }
    hr {
    border-color: #b3b3b3;
  }.row {
    margin-right: -15px;
    margin-left: -15px;
}
  .container {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
  

	</style>


	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Dipshikha's Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to 'Home', '/categories' %></li>
          	<% if @is_creator %>
          		<li><%= link_to 'Delete', @post, method: :delete %></li>
							<li><%= link_to 'Edit', edit_category_post_path %></li>
						<% end %>
            <% if current_user %>
              <li><a method="GET" href="/logout">Logout</a></li>
            <% end %>
						  <li><%= link_to 'Login', '/sessions/new' %></li>

          </ul>
        </div>
      </div>
   	</div>
</br></br>
<div class="container">	
  <div class = "row">
    <div class = "col-md-10 col-md-offset-1">
      <div class = "row">
        <div class = "col-md-8">
          <img width="100%" height="400px;" src="<%= @post.image %>" /></br></br>
	        <h3><%= @post.title %></h3>
	        by  <b><%= @user_name.upcase %></b> created at <%= @post.created_at %>
          </b></br></br>
          <p class = "three-col"><%= @post.content %></p></br></br>
        </div>
        <div class = "col-md-4" style="padding-left:30px;"> 
        <hr>
          <div class = "row">
            <div class = "col-md-12">
              <h5>SEARCH</h5></br>
                <%= form_tag :controller => 'posts', :action => 'search', :method => 'get'  do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search for .....", :id => 'search_field' %>
                  <%= submit_tag "Search", :name => nil, class: "button" %> 
                <% end %> 
            </div>
          </div>
          <hr>
          <div class = "row">
            <div class = "col-md-12">
              <h5>ARCHIVES</h5></br>
                <% @posts_month.each do |month, posts| %>
                  <a href='/archive/<%= month %>'><%= month %></a></br>
                <% end %>
            </div>
          </div>
          <hr>
    </div>
    </div>
    </div>
    </div>
    </div>
  